version: 2
jobs:
    build:
        docker:
            - image: theorangeone/docker-pandoc
        working_directory: ~/labs/
        steps:
            - checkout
            - run: make -C electronics
            - store_artifacts:
                path: electronics/lab.pdf
                destination: electronics.pdf
